/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NNUEVisualization */

#ifndef _Included_NNUEVisualization
#define _Included_NNUEVisualization
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NNUEVisualization
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NNUEVisualization_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     NNUEVisualization
 * Method:    getNeurons
 * Signature: (Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_NNUEVisualization_getNeurons
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
